"""
LangChain tools for the Agentic Boards ReAct agent.

Each tool wraps a discrete capability.  The LLM decides which tools to call
(and in what order) via structured OpenAI-style tool_calls.
"""

from __future__ import annotations

import datetime
import decimal
import json
import logging
import re
import uuid
from typing import Annotated, Any

from langchain_core.tools import tool
from pydantic import BaseModel, Field


def _safe_json_dumps(obj: object, **kwargs) -> str:
    """json.dumps that handles dates, decimals, NaN/Inf floats, and other non-serializable types."""
    import math

    class _Encoder(json.JSONEncoder):
        def default(self, o: object) -> object:
            if isinstance(o, (datetime.date, datetime.datetime)):
                return o.isoformat()
            if isinstance(o, decimal.Decimal):
                return float(o)
            if isinstance(o, (set, frozenset)):
                return list(o)
            return super().default(o)

        def iterencode(self, o: object, _one_shot: bool = False):
            # Walk the structure and replace nan/inf floats with None
            # before encoding so they become JSON null instead of NaN/Infinity
            # (which are not valid JSON and break downstream parsing).
            return super().iterencode(_sanitize(o), _one_shot)

    def _sanitize(v: object) -> object:
        if isinstance(v, float) and (math.isnan(v) or math.isinf(v)):
            return None
        if isinstance(v, dict):
            return {k: _sanitize(val) for k, val in v.items()}
        if isinstance(v, (list, tuple)):
            return [_sanitize(i) for i in v]
        return v

    return json.dumps(obj, cls=_Encoder, **kwargs)

logger = logging.getLogger(__name__)

# ── Fallback metadata when Milvus is off ─────────────────────────────────────
_STATIC_FALLBACK = [
    {
        "cube": "default_table",
        "table": "__REPLACED_AT_RUNTIME__",
        "measures": [],
        "dimensions": [],
        "description": "Run POST /api/databricks/reindex to populate semantic search.",
    },
]


def _get_fallback_metadata() -> list[dict]:
    """Return fallback metadata using the currently configured default table."""
    try:
        from src.databricks.client import get_databricks_manager
        mgr = get_databricks_manager()
        table = mgr.default_table
        catalog = mgr.catalog
        schema = mgr.schema
    except Exception:
        return _STATIC_FALLBACK

    entries = []
    if table:
        entries.append({
            "cube": table.split(".")[-1],
            "table": table,
            "type": "databricks",
            "measures": [],
            "dimensions": [],
            "description": f"Default Databricks table.",
        })
    
    from src.config import settings
    if settings.bigquery_default_table:
        bq_table = settings.bigquery_default_table
        entries.append({
            "cube": bq_table.split(".")[-1],
            "table": bq_table,
            "type": "bigquery",
            "description": "Default BigQuery table. Use execute_bigquery tool for this.",
        })

    if catalog and schema:
        entries.append({
            "hint": f"Browse all tables: SELECT * FROM information_schema.tables WHERE table_catalog='{catalog}' AND table_schema='{schema}'",
            "or_sql": f"SHOW TABLES IN {catalog}.{schema}",
        })
    return entries or _STATIC_FALLBACK


def _parse_llm_json(s: str) -> dict | list:
    """Parse JSON strings generated by LLMs, robustly handling trailing characters / extra braces."""
    s = s.strip()
    try:
        return json.loads(s)
    except json.JSONDecodeError as e:
        # If standard parsing fails, try raw_decode to extract the first valid JSON object
        # and ignore any trailing garbage (like extra '}' added by the LLM).
        try:
            obj, _ = json.JSONDecoder().raw_decode(s)
            return obj
        except json.JSONDecodeError:
            raise e


def _stable_tile_id(prefix: str, payload: object) -> str:
    """Create deterministic tile IDs for idempotent retries in live mode."""
    canonical = json.dumps(payload, sort_keys=True, separators=(",", ":"), default=str)
    return str(uuid.uuid5(uuid.NAMESPACE_URL, f"{prefix}:{canonical}"))


def _extract_rows_payload(raw_rows: object) -> list[object]:
    """Accept common row payload wrappers and return a list."""
    candidate = raw_rows
    if isinstance(candidate, dict):
        if isinstance(candidate.get("rows"), list):
            candidate = candidate.get("rows")
        elif isinstance(candidate.get("data"), list):
            candidate = candidate.get("data")
    return candidate if isinstance(candidate, list) else []


def _extract_columns_payload(raw_columns: object) -> list[object]:
    """Accept common column payload wrappers and return a list."""
    candidate = raw_columns
    if isinstance(candidate, dict):
        if isinstance(candidate.get("columns"), list):
            candidate = candidate.get("columns")
        elif isinstance(candidate.get("fields"), list):
            candidate = candidate.get("fields")
    return candidate if isinstance(candidate, list) else []


def _normalize_table_columns_and_rows(raw_columns: object, raw_rows: object) -> tuple[list[dict[str, str]], list[dict[str, object]]]:
    cols = _extract_columns_payload(raw_columns)
    rows_in = _extract_rows_payload(raw_rows)

    normalized_columns: list[dict[str, str]] = []
    for col in cols:
        field = ""
        header = ""
        if isinstance(col, str):
            field = col.strip()
            header = field
        elif isinstance(col, dict):
            field = str(
                col.get("field")
                or col.get("headerName")
                or col.get("name")
                or col.get("key")
                or col.get("column")
                or col.get("column_name")
                or ""
            ).strip()
            header = str(
                col.get("headerName")
                or col.get("header")
                or col.get("label")
                or col.get("name")
                or col.get("column_name")
                or field
            ).strip()
        if field:
            normalized_columns.append({"field": field, "headerName": header or field})

    # Keep first occurrence for duplicate field names.
    deduped_columns: list[dict[str, str]] = []
    seen_fields: set[str] = set()
    for col in normalized_columns:
        field = col["field"]
        if field in seen_fields:
            continue
        seen_fields.add(field)
        deduped_columns.append(col)
    normalized_columns = deduped_columns

    normalized_rows: list[dict[str, object]] = []
    if rows_in and all(isinstance(r, dict) for r in rows_in):
        normalized_rows = [r for r in rows_in if isinstance(r, dict)]  # type: ignore[list-item]
    elif rows_in and all(isinstance(r, (list, tuple)) for r in rows_in):
        # Convert row arrays to objects using normalized column field order.
        fields = [c["field"] for c in normalized_columns]
        for row in rows_in:
            if not isinstance(row, (list, tuple)):
                continue
            row_dict: dict[str, object] = {}
            for idx, val in enumerate(row):
                key = fields[idx] if idx < len(fields) and fields[idx] else f"column_{idx + 1}"
                row_dict[key] = val
            normalized_rows.append(row_dict)
    elif rows_in:
        normalized_rows = [{"value": v} for v in rows_in]

    if (not normalized_columns) and normalized_rows:
        first = normalized_rows[0]
        normalized_columns = [{"field": k, "headerName": k} for k in first.keys()]

    return normalized_columns, normalized_rows

# ═════════════════════════════════════════════════════════════════════════════
# Tool 1 – Search Metadata
# ═════════════════════════════════════════════════════════════════════════════

class SearchMetadataInput(BaseModel):
    """Input for the search_metadata tool."""
    query: str = Field(description="Natural language description of the data the user wants, e.g. 'sales by region' or 'top customers by revenue'")


@tool("search_metadata", args_schema=SearchMetadataInput)
def search_metadata(query: str) -> str:
    """Search for relevant data sources (BigQuery or Databricks).

    Always call this FIRST before writing SQL to find the correct table names,
    columns, and connection type (BigQuery vs Databricks).
    """
    from src.config import settings
    from src.databricks.client import get_databricks_manager
    from src.bigquery.client import get_bigquery_manager
    from src.metadata import schema_cache

    results = []

    # 1. Try Milvus Vector Search (Cross-provider)
    if settings.milvus_enabled:
        try:
            from src.metadata.databricks_store import DatabricksMetadataStore
            store = DatabricksMetadataStore()
            hits = store.search(query, top_k=15)
            good_hits = [h for h in hits if h.get("score", 0) >= 0.35]
            if good_hits:
                logger.info("[TOOL:search_metadata] Milvus found %d relevant items", len(good_hits))
                results.extend(_hits_to_metadata(good_hits))
        except Exception as e:
            logger.warning("[TOOL:search_metadata] Milvus lookup skipped: %s", e)

    # 2. Check BigQuery Default Table
    bq = get_bigquery_manager()
    if bq.default_table and query.lower() in bq.default_table.lower():
        results.append({
            "cube": bq.default_table.split(".")[-1],
            "table": bq.default_table,
            "type": "bigquery",
            "description": "Primary BigQuery table for this project."
        })

    # 3. Check Databricks Cache (if connected)
    dm = get_databricks_manager()
    if dm.is_connected:
        try:
            cache_hits = schema_cache.search(
                query=query,
                catalog=dm.catalog,
                schema=dm.schema,
                top_k=5,
            )
            if cache_hits:
                results.extend(cache_hits)
        except Exception as e:
            logger.warning("[TOOL:search_metadata] Databricks cache lookup failed: %s", e)
    
    # 4. Filter and return
    if results:
        # De-duplicate by table name
        seen = set()
        unique_results = []
        for r in results:
            t = r.get("table")
            if t and t not in seen:
                unique_results.append(r)
                seen.add(t)
        return json.dumps(unique_results, indent=2)

    # 5. Last resort: Static fallback
    logger.info("[TOOL:search_metadata] No dynamic hits — using static fallback")
    return json.dumps(_get_fallback_metadata(), indent=2)


def _hits_to_metadata(hits: list[dict]) -> list[dict]:
    """Group column-level Milvus hits into per-table metadata dicts."""
    from collections import defaultdict

    tables: dict[str, dict] = defaultdict(lambda: {
        "table": "",
        "type": "databricks",
        "columns": [],
        "measures": [],
        "dimensions": [],
        "categorical_values": {},
        "analysis_guide": "",
    })

    for hit in hits:
        tbl = hit.get("table_name", "")
        doc_type = hit.get("doc_type", "")
        meta = hit.get("metadata", {})
        if not tbl:
            continue

        tables[tbl]["table"] = tbl

        if doc_type == "table":
            tables[tbl]["columns"] = meta.get("columns", [])
        elif doc_type == "column":
            col_name = hit.get("column_name", meta.get("column_name", ""))
            dtype = meta.get("data_type", "")
            is_numeric = any(t in dtype for t in ("Long", "Int", "Double", "Float", "Short", "Decimal"))
            full_ref = f"{tbl}.{col_name}"
            if is_numeric:
                tables[tbl]["measures"].append(full_ref)
            else:
                tables[tbl]["dimensions"].append(full_ref)
        elif doc_type == "categorical":
            col_name = hit.get("column_name", meta.get("column_name", ""))
            tables[tbl]["categorical_values"][col_name] = meta.get("distinct_values", [])
        elif doc_type == "analysis_guide":
            tables[tbl]["analysis_guide"] = hit.get("text", "")

    return [
        {
            "cube": tbl.split(".")[-1],
            "table": data["table"],
            "measures": data["measures"],
            "dimensions": data["dimensions"],
            "categorical_values": data["categorical_values"],
            "analysis_guide": data["analysis_guide"],
            "columns": data["columns"],
        }
        for tbl, data in tables.items()
    ]


# ═════════════════════════════════════════════════════════════════════════════
# Tool 2 – Execute SQL
# ═════════════════════════════════════════════════════════════════════════════

class ExecuteSQLInput(BaseModel):
    """Input for the execute_sql tool."""
    sql: str = Field(description="A valid Databricks SQL query using fully-qualified table names (catalog.schema.table). Must include LIMIT unless doing aggregation.")


class ExecuteBigQueryInput(BaseModel):
    """Input for the execute_bigquery tool."""
    sql: str = Field(description="A valid Google BigQuery SQL query (standard SQL). Use backticks for table names. Must include LIMIT unless doing aggregation.")


class GetBigQuerySchemaInput(BaseModel):
    """Input for the get_bigquery_schema tool."""
    table_name: str = Field(description="The fully-qualified BigQuery table name (project.dataset.table).")


@tool("get_bigquery_schema", args_schema=GetBigQuerySchemaInput)
def get_bigquery_schema(table_name: str) -> str:
    """Get the column definitions (schema) for a specific BigQuery table.
    Use this if you know a table exists (e.g. from search_metadata) but don't know its columns.
    """
    from src.bigquery.client import get_bigquery_manager
    bq = get_bigquery_manager()
    
    # Sanitize the table name - it might come in with backticks or dots
    clean_table = table_name.strip("`")
    parts = clean_table.split(".")
    if len(parts) < 3:
        return f"Error: '{table_name}' is not a fully-qualified BigQuery table name (project.dataset.table)."
    
    project_id, dataset_id, table_id = parts[0], parts[1], parts[2]
    
    # In BigQuery standard SQL, INFORMATION_SCHEMA is scoped to the dataset
    sql = f"""
    SELECT column_name, data_type 
    FROM `{project_id}`.{dataset_id}.INFORMATION_SCHEMA.COLUMNS 
    WHERE table_name = '{table_id}'
    """
    
    try:
        rows = bq.query(sql)
        if not rows:
            return f"No schema found for table '{table_name}'. Verify the table exists."
        return _safe_json_dumps(rows, indent=2)
    except Exception as e:
        return f"Error fetching schema: {str(e)}"


@tool("execute_bigquery", args_schema=ExecuteBigQueryInput)
def execute_bigquery(sql: str) -> str:
    """Execute a SQL query on Google BigQuery and return the result rows.
    
    Use this for BigQuery tables (e.g. agentic-boards.iowa_liquor_retail_sales.sales).
    Standard SQL syntax is required.
    """
    from src.bigquery.client import get_bigquery_manager
    bq = get_bigquery_manager()
    
    try:
        logger.info("[TOOL:execute_bigquery] %s", sql[:200])
        pdf = bq.query_pandas(sql)
        rows = pdf.to_dict(orient="records")
        return _safe_json_dumps({"rows": rows, "row_count": len(rows)})
    except Exception as e:
        logger.error("[TOOL:execute_bigquery] failed: %s", e)
        return _safe_json_dumps({"error": str(e), "rows": []})


@tool("execute_sql", args_schema=ExecuteSQLInput)
def execute_sql(sql: str) -> str:
    """Execute a SQL query on the Databricks warehouse and return the
    result rows as a JSON array.

    Call search_metadata first to discover available tables and columns,
    then write a SQL query targeting those tables.
    """
    # ── SQL injection / write-operation guard ─────────────────────────────────
    from src.databricks.sql_validator import validate_sql_read_only, InvalidSQLError
    try:
        validate_sql_read_only(sql)
    except InvalidSQLError as e:
        return json.dumps({
            "error": str(e),
            "rows": [],
        })
    # ── End guard ─────────────────────────────────────────────────────────────

    from src.databricks.client import get_databricks_manager

    dm = get_databricks_manager()

    if not dm.is_connected:
        logger.warning("[TOOL:execute_sql] Databricks not connected")
        return json.dumps({"error": "Databricks is not connected.", "rows": []})

    try:
        import math
        import pandas as _pd

        logger.info("[TOOL:execute_sql] %s", sql[:200])
        pdf = dm.query_pandas(sql)
        rows = pdf.to_dict(orient="records")
        logger.info("[TOOL:execute_sql] returned %d rows", len(rows))

        # ── Post-query data-quality check ─────────────────────────────────
        # Detect when every numeric column is all-null or all-zero — this
        # almost always means the query hit a "No Data" period.  Alert the
        # agent so it re-queries instead of charting meaningless zeroes.
        warning: str | None = None
        if rows:
            num_cols = [
                c for c in pdf.columns
                if _pd.api.types.is_numeric_dtype(pdf[c])
            ]
            if num_cols:
                all_empty = all(
                    pdf[c].apply(
                        lambda v: v is None or (isinstance(v, float) and (math.isnan(v) or v == 0.0)) or v == 0
                    ).all()
                    for c in num_cols
                )
                if all_empty:
                    warning = (
                        "DATA QUALITY WARNING: all numeric columns are zero or null. "
                        "This period likely contains no real data. "
                        "Do NOT visualise this result. "
                        "Re-run the query targeting a different period that has actual non-zero values. "
                        "Do NOT apply COALESCE or replace nulls with 0."
                    )
                    logger.warning("[TOOL:execute_sql] all-zero/null result — likely a 'No Data' period")

        result: dict = {"rows": rows, "row_count": len(rows)}
        if warning:
            result["warning"] = warning
        return _safe_json_dumps(result)
    except Exception as e:
        err_str = str(e)
        logger.error("[TOOL:execute_sql] failed: %s", err_str)
        # Surface a concise, actionable message for view schema errors
        if "INCOMPATIBLE_VIEW_SCHEMA_CHANGE" in err_str:
            table_hint = sql.split("FROM")[-1].split()[0] if "FROM" in sql.upper() else "unknown"
            return _safe_json_dumps({
                "error": (
                    f"INCOMPATIBLE_VIEW_SCHEMA_CHANGE: The VIEW '{table_hint}' has a stale schema. "
                    "Do NOT retry with this view. Re-run the query using the underlying base table directly "
                    "(e.g. gold_variancesummary instead of vw_variance_with_hierarchies)."
                ),
                "rows": [],
            })
        return _safe_json_dumps({"error": err_str, "rows": []})


# ═════════════════════════════════════════════════════════════════════════════
# Tool 3 – Create Visualization
# ═════════════════════════════════════════════════════════════════════════════

class CreateVisualizationInput(BaseModel):
    """Input for the create_visualization tool."""
    vega_lite_spec: str = Field(
        description=(
            "A COMPLETE Vega-Lite v5 JSON specification as a string. "
            "Must include $schema, data.values (the actual data rows), "
            "mark, encoding, and a descriptive title. "
            "Use 'container' for width."
        )
    )


@tool("create_visualization", args_schema=CreateVisualizationInput)
def create_visualization(vega_lite_spec: str) -> str:
    """Add a new chart tile to the user's dashboard.

    Provide a COMPLETE Vega-Lite v5 JSON spec with the data already
    embedded in data.values. The chart will appear as a new tile on the
    dashboard.
    """
    try:
        spec = _parse_llm_json(vega_lite_spec)
    except json.JSONDecodeError as e:
        return json.dumps({"error": f"Invalid JSON: {e}"})

    if "$schema" not in spec:
        spec["$schema"] = "https://vega.github.io/schema/vega-lite/v5.json"

    tile_id = str(uuid.uuid4())

    logger.info(
        "[TOOL:create_visualization] tile=%s  mark=%s  rows=%d",
        tile_id,
        spec.get("mark", "?"),
        len((spec.get("data") or {}).get("values", [])),
    )

    return json.dumps({
        "action": "create_visualization",
        "tile_id": tile_id,
        "vega_spec": spec,
    })


# ═════════════════════════════════════════════════════════════════════════════
# Tool 4 – Modify Dashboard  (specs and / or layouts)
# ═════════════════════════════════════════════════════════════════════════════

class ModifyDashboardInput(BaseModel):
    """Input for the modify_dashboard tool."""
    modifications: str | dict[str, Any] | list[dict[str, Any]] = Field(
        description=(
            'A JSON object (or JSON string of that object) with any combination of these optional keys: '
            '"spec_updates" (array of {tile_id, vega_spec}) to change chart appearance; '
            '"layout_updates" (array of {tile_id, x, y, w, h}) to reposition/resize on the 12-column grid; '
            '"title_updates" (array of {tile_id, title}) to rename the tile header label; '
            '"kpi_updates" (array of {tile_id, value, subtitle, color}) to modify metric cards; '
            '"text_updates" (array of {tile_id, markdown}) to update the content of a text/markdown tile. '
            'Each row ≈ 100px. w goes from 1–12 (12=full width).'
        )
    )


@tool("modify_dashboard", args_schema=ModifyDashboardInput)
def modify_dashboard(modifications: str | dict[str, Any] | list[Any]) -> str:
    """Modify existing dashboard tiles — change chart specs (colours, marks,
    axis labels), rename tile header labels, and/or reposition / resize tiles
    on the 12-column grid.

    Use title_updates to rename the tile's header label (the banner shown above
    the chart/table). This is SEPARATE from the Vega-Lite chart title inside
    the visualisation itself.

    Layout coordinates:
    - x: column (0-11), left-to-right
    - y: row (0+), top-to-bottom
    - w: width in columns (1-12, 12=full width, 6=half)
    - h: height in row units (each row ≈ 100px, typical chart h=3-5)
    """
    if isinstance(modifications, str):
        try:
            mods = _parse_llm_json(modifications)
        except json.JSONDecodeError as e:
            return json.dumps({"error": f"Invalid JSON: {e}"})
    elif isinstance(modifications, (dict, list)):
        mods = modifications
    else:
        return json.dumps({"error": "Invalid modifications payload type."})

    # The live model may occasionally return a top-level JSON array instead of the
    # expected object. Normalize common list shapes so we can recover instead of
    # throwing and killing the live session.
    if isinstance(mods, list):
        if not mods:
            mods = {}
        else:
            normalized_items: list[dict] = []
            for item in mods:
                if isinstance(item, str):
                    try:
                        parsed = _parse_llm_json(item)
                        if isinstance(parsed, dict):
                            normalized_items.append(parsed)
                    except json.JSONDecodeError:
                        logger.warning("[TOOL:modify_dashboard] ignored non-JSON list item: %r", item[:120])
                elif isinstance(item, dict):
                    normalized_items.append(item)

            if not normalized_items:
                mods = {}
            else:
                bucketed: dict[str, list[dict]] = {
                    "spec_updates": [],
                    "layout_updates": [],
                    "title_updates": [],
                    "kpi_updates": [],
                    "text_updates": [],
                }
                for item in normalized_items:
                    tile_id = item.get("tile_id")

                    if "spec_updates" in item:
                        spec_val = item.get("spec_updates")
                        if isinstance(spec_val, list):
                            bucketed["spec_updates"].extend([u for u in spec_val if isinstance(u, dict)])
                        elif isinstance(spec_val, dict):
                            spec_upd = dict(spec_val)
                            if tile_id and "tile_id" not in spec_upd:
                                spec_upd["tile_id"] = tile_id
                            bucketed["spec_updates"].append(spec_upd)
                        continue

                    if "layout_updates" in item:
                        layout_val = item.get("layout_updates")
                        if isinstance(layout_val, list):
                            bucketed["layout_updates"].extend([u for u in layout_val if isinstance(u, dict)])
                        elif isinstance(layout_val, dict):
                            layout_upd = dict(layout_val)
                            if tile_id and "tile_id" not in layout_upd:
                                layout_upd["tile_id"] = tile_id
                            bucketed["layout_updates"].append(layout_upd)
                        continue

                    if "title_updates" in item:
                        title_val = item.get("title_updates")
                        if isinstance(title_val, list):
                            bucketed["title_updates"].extend([u for u in title_val if isinstance(u, dict)])
                        elif isinstance(title_val, dict):
                            title_upd = dict(title_val)
                            if tile_id and "tile_id" not in title_upd:
                                title_upd["tile_id"] = tile_id
                            bucketed["title_updates"].append(title_upd)
                        continue

                    if "kpi_updates" in item:
                        kpi_val = item.get("kpi_updates")
                        if isinstance(kpi_val, list):
                            bucketed["kpi_updates"].extend([u for u in kpi_val if isinstance(u, dict)])
                        elif isinstance(kpi_val, dict):
                            kpi_upd = dict(kpi_val)
                            if tile_id and "tile_id" not in kpi_upd:
                                kpi_upd["tile_id"] = tile_id
                            bucketed["kpi_updates"].append(kpi_upd)
                        continue

                    if "text_updates" in item:
                        text_val = item.get("text_updates")
                        if isinstance(text_val, list):
                            bucketed["text_updates"].extend([u for u in text_val if isinstance(u, dict)])
                        elif isinstance(text_val, dict):
                            text_upd = dict(text_val)
                            if tile_id and "tile_id" not in text_upd:
                                text_upd["tile_id"] = tile_id
                            bucketed["text_updates"].append(text_upd)
                        continue

                    if "vega_spec" in item:
                        bucketed["spec_updates"].append(item)
                    elif all(k in item for k in ("x", "y", "w", "h")):
                        bucketed["layout_updates"].append(item)
                    elif "markdown" in item:
                        bucketed["text_updates"].append(item)
                    elif any(k in item for k in ("value", "subtitle", "color")):
                        bucketed["kpi_updates"].append(item)
                    elif "title" in item:
                        bucketed["title_updates"].append(item)

                mods = {k: v for k, v in bucketed.items() if v}

    if not isinstance(mods, dict):
        return json.dumps({"error": "Invalid modifications payload. Expected an object or list of update objects."})

    def _as_update_list(value: object) -> list[dict[str, Any]]:
        if isinstance(value, list):
            return [v for v in value if isinstance(v, dict)]
        if isinstance(value, dict):
            return [value]
        return []

    def _with_tile_id(update: dict[str, Any]) -> dict[str, Any]:
        tile_id = update.get("tile_id") or update.get("tileId")
        if tile_id and "tile_id" not in update:
            return {**update, "tile_id": tile_id}
        return update

    result: dict = {"action": "modify_dashboard"}

    spec_updates = _as_update_list(mods.get("spec_updates") or mods.get("specUpdates"))
    layout_updates = _as_update_list(mods.get("layout_updates") or mods.get("layoutUpdates"))
    title_updates = _as_update_list(mods.get("title_updates") or mods.get("titleUpdates"))
    kpi_updates = _as_update_list(mods.get("kpi_updates") or mods.get("kpiUpdates"))
    text_updates = _as_update_list(mods.get("text_updates") or mods.get("textUpdates"))

    if spec_updates:
        # Normalise each spec_update: parse vega_spec if the LLM sent it as a
        # JSON string instead of an object, and inject $schema if missing.
        normalised_spec_updates = []
        for su in spec_updates:
            su = _with_tile_id(su)
            vs = su.get("vega_spec") or su.get("vegaSpec") or su.get("spec")
            if vs is None:
                # Some model outputs place patch keys directly on the update
                # object (alongside tile_id) instead of nesting under vega_spec.
                # Treat the remaining keys as a partial Vega-Lite patch.
                direct_patch = {
                    k: v
                    for k, v in su.items()
                    if k not in ("tile_id", "tileId", "vega_spec", "vegaSpec", "spec")
                }
                if direct_patch:
                    vs = direct_patch
            if isinstance(vs, str):
                try:
                    vs = _parse_llm_json(vs)
                except json.JSONDecodeError as e:
                    return json.dumps({"error": f"Invalid vega_spec JSON in spec_updates: {e}"})
            if isinstance(vs, dict) and "$schema" not in vs and any(k in vs for k in ("mark", "encoding", "layer", "data")):
                vs["$schema"] = "https://vega.github.io/schema/vega-lite/v5.json"
            normalised_spec_updates.append({**su, "vega_spec": vs})
        
        if normalised_spec_updates:
            result["spec_updates"] = normalised_spec_updates
            logger.info(
                "[TOOL:modify_dashboard] spec updates for tile(s): %s",
                [u.get("tile_id") for u in normalised_spec_updates],
            )

    if layout_updates:
        valid_layout_updates = [_with_tile_id(u) for u in layout_updates]
        if valid_layout_updates:
            result["layout_updates"] = valid_layout_updates
            logger.info(
                "[TOOL:modify_dashboard] layout updates for tile(s): %s",
                [u.get("tile_id") for u in valid_layout_updates],
            )

    if title_updates:
        valid_title_updates = [_with_tile_id(u) for u in title_updates]
        if valid_title_updates:
            result["title_updates"] = valid_title_updates
            logger.info(
                "[TOOL:modify_dashboard] title updates for tile(s): %s",
                [u.get("tile_id") for u in valid_title_updates],
            )

    if kpi_updates:
        valid_kpi_updates = [_with_tile_id(u) for u in kpi_updates]
        if valid_kpi_updates:
            result["kpi_updates"] = valid_kpi_updates
            logger.info(
                "[TOOL:modify_dashboard] kpi updates for tile(s): %s",
                [u.get("tile_id") for u in valid_kpi_updates],
            )

    if text_updates:
        valid_text_updates = [_with_tile_id(u) for u in text_updates]
        if valid_text_updates:
            result["text_updates"] = valid_text_updates
            logger.info(
                "[TOOL:modify_dashboard] text updates for tile(s): %s",
                [u.get("tile_id") for u in valid_text_updates],
            )

    if not any(k in result for k in ("spec_updates", "layout_updates", "title_updates", "kpi_updates", "text_updates")):
        result["error"] = "No spec_updates, layout_updates, title_updates, kpi_updates, or text_updates provided."

    return json.dumps(result)


# ═════════════════════════════════════════════════════════════════════════════
# Tool 5 – Create Data Table  (interactive table tile)
# ═════════════════════════════════════════════════════════════════════════════

class CreateDataTableInput(BaseModel):
    """Input for the create_data_table tool."""
    title: str = Field(description="A descriptive title for the table tile.")
    columns: str = Field(
        description=(
            'JSON array of column definitions: [{"field": "col_name", "headerName": "Display Name"}, ...]. '
            'field must match a key in the row objects.'
        )
    )
    rows: str = Field(
        description=(
            'JSON array of row objects: [{"col1": val1, "col2": val2}, ...].  '
            'Pass the rows exactly as returned by execute_sql.'
        )
    )


@tool("create_data_table", args_schema=CreateDataTableInput)
def create_data_table(title: str, columns: str, rows: str) -> str:
    """Add an interactive data-table tile to the dashboard.

    Use this instead of create_visualization when the user asks to
    **show a table**, **list rows**, **display data in tabular form**,
    or says keywords like "table", "spreadsheet", "grid", "rows".

    The table supports sorting, filtering/search, pagination, and scrolling.
    """
    try:
        col_defs = _parse_llm_json(columns)
    except json.JSONDecodeError as e:
        return _safe_json_dumps({"error": f"Invalid columns JSON: {e}"})

    try:
        row_data = _parse_llm_json(rows)
    except json.JSONDecodeError as e:
        return _safe_json_dumps({"error": f"Invalid rows JSON: {e}"})

    normalized_columns, normalized_rows = _normalize_table_columns_and_rows(col_defs, row_data)

    tile_id = str(uuid.uuid4())

    logger.info(
        "[TOOL:create_data_table] tile=%s  cols=%d  rows=%d",
        tile_id, len(normalized_columns), len(normalized_rows),
    )

    return _safe_json_dumps({
        "action": "create_data_table",
        "tile_id": tile_id,
        "title": title,
        "columns": normalized_columns,
        "rows": normalized_rows,
    })


# ═════════════════════════════════════════════════════════════════════════════
# Tool 6 – Update Data Table  (replace table data in-place)
# ═════════════════════════════════════════════════════════════════════════════

class UpdateDataTableInput(BaseModel):
    """Input for the update_data_table tool."""
    tile_id: str = Field(description="The tile_id of the existing table tile to update.")
    title: str = Field(description="Updated title for the table tile.")
    columns: str = Field(
        description=(
            'JSON array of column definitions: [{"field": "col_name", "headerName": "Display Name"}, ...]. '
            'field must match a key in the row objects.'
        )
    )
    rows: str = Field(
        description=(
            'JSON array of row objects: [{"col1": val1, "col2": val2}, ...].  '
            'Pass the rows exactly as returned by execute_sql.'
        )
    )


@tool("update_data_table", args_schema=UpdateDataTableInput)
def update_data_table(tile_id: str, title: str, columns: str, rows: str) -> str:
    """Update an EXISTING data-table tile on the dashboard with new data.

    Use this instead of create_data_table when the user wants to modify
    an existing table — e.g. "show more rows", "add a column",
    "filter to last month", "sort by revenue".

    Provide the tile_id of the existing tile and the new column definitions
    and row data.
    """
    try:
        col_defs = _parse_llm_json(columns)
    except json.JSONDecodeError as e:
        return _safe_json_dumps({"error": f"Invalid columns JSON: {e}"})

    try:
        row_data = _parse_llm_json(rows)
    except json.JSONDecodeError as e:
        return _safe_json_dumps({"error": f"Invalid rows JSON: {e}"})

    normalized_columns, normalized_rows = _normalize_table_columns_and_rows(col_defs, row_data)

    logger.info(
        "[TOOL:update_data_table] tile=%s  cols=%d  rows=%d",
        tile_id, len(normalized_columns), len(normalized_rows),
    )

    return _safe_json_dumps({
        "action": "update_data_table",
        "tile_id": tile_id,
        "title": title,
        "columns": normalized_columns,
        "rows": normalized_rows,
    })


# ═════════════════════════════════════════════════════════════════════════════
# All tools list (used by graph.py)
# ═════════════════════════════════════════════════════════════════════════════

# ═════════════════════════════════════════════════════════════════════════════
# Tool 7 – Remove Tile  (delete a tile from the dashboard)
# ═════════════════════════════════════════════════════════════════════════════

class RemoveTilesInput(BaseModel):
    """Input for the remove_tiles tool."""
    tile_ids: list[str] = Field(
        description="List of tile_id values to remove from the dashboard. Use the tile_ids from the dashboard context."
    )


@tool("remove_tiles", args_schema=RemoveTilesInput)
def remove_tiles(tile_ids: list[str]) -> str:
    """Remove one or more tiles from the dashboard.

    Use this when the user asks to remove, delete, close, or clear
    specific tiles. Provide the tile_id(s) from the current dashboard context.
    """
    if not tile_ids:
        return json.dumps({"error": "No tile_ids provided."})

    logger.info("[TOOL:remove_tiles] removing tiles: %s", tile_ids)
    return json.dumps({"action": "remove_tiles", "tile_ids": tile_ids})



# ═════════════════════════════════════════════════════════════════════════════
# Tool 8 – Create KPI Tile  (Power BI-style metric card)
# ═════════════════════════════════════════════════════════════════════════════

class CreateKpiTileInput(BaseModel):
    """Input for the create_kpi_tile tool."""
    title: str = Field(
        description="The main label shown in smaller text above the value (e.g. 'Total Revenue', 'Tokyo Tidbits')."
    )
    value: str = Field(
        description="The primary metric value to display prominently (e.g. '$10,986', '42.5%', '1,234')."
    )
    subtitle: str = Field(
        default="",
        description="Optional secondary line shown below the value in smaller text (e.g. product name, date range, comparison)."
    )
    color: str = Field(
        default="",
        description="Optional accent color for the value text as a hex code (e.g. '#22c55e' for green, '#ef4444' for red). Leave empty for default."
    )
    sparkline_data: str = Field(
        default="",
        description="Optional JSON array of numeric values to render a sparkline trend chart beneath the KPI (e.g. '[10, 20, 15, 30]')."
    )
    tile_id: str = Field(
        default="",
        description="Optional explicit tile_id. If omitted, a deterministic ID is derived from KPI content for idempotent retries."
    )

@tool("create_kpi_tile", args_schema=CreateKpiTileInput)
def create_kpi_tile(title: str, value: str, subtitle: str = "", color: str = "", sparkline_data: str = "", tile_id: str = "") -> str:
    """Add a Power BI-style KPI / metric card tile to the dashboard.

    Use this when the user wants a simple number / metric displayed
    prominently — e.g. \"show total revenue\", \"display the count\",
    \"create a KPI card\", or when the SQL result is a single aggregated value.

    The card shows:
      - Top line (smaller):  title / label
      - Middle (large font): the metric value
      - Bottom (smaller):    optional subtitle / context

    Examples: total revenue, average order value, record count, % change.
    """
    if not tile_id:
        tile_id = _stable_tile_id(
            "kpi",
            {
                "title": title.strip(),
                "value": value.strip(),
                "subtitle": subtitle.strip(),
                "color": color.strip(),
                "sparkline_data": sparkline_data.strip(),
            },
        )

    logger.info(
        "[TOOL:create_kpi_tile] tile=%s  title=%r  value=%r",
        tile_id, title, value,
    )

    return _safe_json_dumps({
        "action": "create_kpi_tile",
        "tile_id": tile_id,
        "title": title,
        "value": value,
        "subtitle": subtitle,
        "color": color,
        "sparkline_data": sparkline_data,
    })


# ═════════════════════════════════════════════════════════════════════════════
# Tool 9 – Create Text Tile (Markdown annotations / headers)
# ═════════════════════════════════════════════════════════════════════════════

class CreateTextTileInput(BaseModel):
    """Input for the create_text_tile tool."""
    title: str = Field(
        description="The title of the tile, shown in the header bar."
    )
    markdown: str = Field(
        description="The text content to display, using Markdown formatting (headings, lists, bold, etc.)."
    )

@tool("create_text_tile", args_schema=CreateTextTileInput)
def create_text_tile(title: str, markdown: str) -> str:
    """Add a Markdown / Text tile to the dashboard.

    Use this when the user asks to add notes, headers, explanations,
    executive summaries, or text annotations that aren't tied to a specific metric.
    """
    tile_id = str(uuid.uuid4())
    logger.info("[TOOL:create_text_tile] tile=%s  title=%r", tile_id, title)

    return _safe_json_dumps({
        "action": "create_text_tile",
        "tile_id": tile_id,
        "title": title,
        "markdown": markdown,
    })


# ═════════════════════════════════════════════════════════════════════════════
# All tools list (used by graph.py)
# ═════════════════════════════════════════════════════════════════════════════

ALL_TOOLS = [
    search_metadata,
    execute_sql,
    execute_bigquery,
    create_visualization,
    create_kpi_tile,
    create_data_table,
    update_data_table,
    create_text_tile,
    modify_dashboard,
    remove_tiles,
]
